#!/bin/bash -e

. config.conf

BASEDIR=$(pwd)

if [ "$SETUP_PACKAGES" == "1" ]
then
    # Setup Java 8
    sudo add-apt-repository -y ppa:webupd8team/java
    sudo apt-get update
    sudo apt-get purge -y openjdk*
    echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
    echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
    sudo apt-get -y install oracle-java8-installer ant

    DEPS="vim git curl bzip2 gcc g++ binutils make autoconf openssl \
          libssl-dev ant libopus0 \
          libpcre3 libpcre3-dev build-essential nasm \
          libc6:i386 libstdc++6:i386 zlib1g:i386"
    sudo -- sh -c "dpkg --add-architecture i386; apt-get update && apt-get -y upgrade && apt-get install -y ${DEPS}"
fi

if [ "$DOWNLOAD_NDK" == "1" ]
then
    echo "Downloading Android NDK ..."
    cd "${BASEDIR}"
    curl -L -# -o ndk.bin "$NDK_DOWNLOAD_URL" 2>&1
    rm -rf "$NDK_DIR_NAME"
    echo "Android NDK downloaded!"
    echo "Extracting Android NDK ..."
    chmod +x ndk.bin && ./ndk.bin 2>&1 > /dev/null || true
    rm -rf ndk.bin
fi

if [ "$DOWNLOAD_SDK" == "1" ]
then
    echo "Downloading Android SDK ..."
    cd "${BASEDIR}"
    curl -L -# -o sdk.tgz "$SDK_DOWNLOAD_URL" 2>&1
    rm -rf "$SDK_DIR_NAME"
    echo "Android SDK downloaded!"
    echo "Extracting Android SDK ..."
    tar xzf sdk.tgz && rm -rf sdk.tgz
fi

if [ "$DOWNLOAD_ANDROID_APIS" == "1" ]
then
    cd ${BASEDIR}/${SDK_DIR_NAME}/tools

    ALL_SDK=$(./android list sdk --all)

    for api in "${SETUP_ANDROID_APIS[@]}"
    do
        echo "Downloading Android API Platform ${api}..."
        PACKAGE=$(echo "${ALL_SDK}" | grep "API ${api}" | head -n 1 | awk '{print $1}' | cut -d'-' -f 1)
        echo yes | ./android update sdk --all --filter ${PACKAGE} --no-ui --force
    done

    PACKAGE=$(echo "${ALL_SDK}" | grep "Android SDK Platform-tools" | head -n 1 | awk '{print $1}' | cut -d'-' -f 1)
    echo yes | ./android update sdk --all --filter ${PACKAGE} --no-ui --force

    PACKAGE=$(echo "${ALL_SDK}" | grep "Build-tools" | grep "${BUILD_TOOLS_VERSION}" | head -n 1 | awk '{print $1}' | cut -d'-' -f 1)
    echo yes | ./android update sdk --all --filter ${PACKAGE} --no-ui --force
fi

if [ "$DOWNLOAD_PJSIP" == "1" ]
then
    echo "Downloading PJSIP ..."
    cd "${BASEDIR}"
    curl -L -# -o pjsip.tar.bz2 "$PJSIP_DOWNLOAD_URL" 2>&1
    rm -rf "$PJSIP_DIR_NAME"
    echo "PJSIP downloaded!"
    echo "Extracting PJSIP ..."
    tar xjf pjsip.tar.bz2 && rm -rf pjsip.tar.bz2

    if [ "${PJSIP_DIR_NAME}" == "pjproject-2.4.5" ]
    then
        echo "Fix BASH script error in 2.4.5 tag ..."
        sed -i 's/TARGET_HOST+=-linux-android/TARGET_HOST="\${TARGET_HOST}-linux-android"/g' "${BASEDIR}/${PJSIP_DIR_NAME}/configure-android"

        echo "Apply patch to support G.729 codec without Intel IPP codec library ..."
        cd g729_patch
        ./install.sh
        cd ..
    fi
fi

if [ "$DOWNLOAD_SWIG" == "1" ]
then
    echo "Downloading SWIG ..."
    cd "${BASEDIR}"
    curl -L -# -o swig.tar.gz "$SWIG_DOWNLOAD_URL" 2>&1
    rm -rf "$SWIG_DIR_NAME"
    echo "SWIG downloaded!"
    echo "Extracting SWIG ..."
    tar xzf swig.tar.gz && rm -rf swig.tar.gz
    cd "$SWIG_DIR_NAME"
    ./configure
    make && sudo make install
    cd ..
    rm -rf "$SWIG_DIR_NAME"
fi

if [ "$DOWNLOAD_OPENSSL" == "1" ]
then
    echo "Downloading OpenSSL ..."
    cd "${BASEDIR}"
    curl -L -# -o openssl.tar.gz "$OPENSSL_DOWNLOAD_URL" 2>&1
    rm -rf "$OPENSSL_DIR_NAME"
    echo "OpenSSL downloaded!"
    echo "Extracting OpenSSL ..."
    tar xzf openssl.tar.gz && rm -rf openssl.tar.gz
    cd ${BASEDIR}
    ./openssl-build-target-archs
fi

if [ "$DOWNLOAD_LIBYUV" == "1" ]
then
    echo "Downloading libyuv ..."
    cd "${BASEDIR}"
    rm -rf "${LIBYUV_REPO_DIR_NAME}"
    git clone "${LIBYUV_REPO_PATH}"
    cd "${LIBYUV_REPO_DIR_NAME}"
    export PATH="${BASEDIR}/${NDK_DIR_NAME}:$PATH"

    # Re-enable static library, disabled with https://github.com/illuspas/libyuv-android/commit/d5d7e66ed635cf96fce1aa029ccc24a06bb0e7bc
    sed -i 's/#include $(BUILD_SHARED_LIBRARY)/include $(BUILD_SHARED_LIBRARY)/g' jni/Android.mk
    sed -i 's/include $(BUILD_STATIC_LIBRARY)/#include $(BUILD_STATIC_LIBRARY)/g' jni/Android.mk   

    if [ "${OPENH264_TARGET_NDK_LEVEL}" -ge "21" ]
    then
        sed -i 's/APP_ABI := armeabi-v7a arm64-v8a x86 x86_64/APP_ABI := armeabi armeabi-v7a arm64-v8a x86 x86_64 mips mips64/g' jni/Application.mk
    else
        sed -i 's/APP_ABI := armeabi-v7a arm64-v8a x86 x86_64/APP_ABI := armeabi armeabi-v7a x86/g' jni/Application.mk
    fi

    ndk-build
fi

if [ "$DOWNLOAD_OPENH264" == "1" ]
then
    echo "Downloading OpenH264 ..."
    cd "${BASEDIR}"
    curl -L -# -o openh264.tar.gz "$OPENH264_DOWNLOAD_URL" 2>&1
    rm -rf "${OPENH264_DIR_NAME}"
    echo "OpenH264 downloaded!"
    echo "Extracting OpenH264 ..."
    tar xzf openh264.tar.gz && rm -rf openh264.tar.gz
    if [ "${OPENH264_DIR_NAME}" == "openh264-1.0.0" ] && [ "${OPENH264_TARGET_NDK_LEVEL}" -ge "21" ]
    then
        echo "Patching OpenH264 to be able to compile with Android API 21+.."
        cp ${BASEDIR}/openh264-1.0.0-android21.patch ${BASEDIR}/${OPENH264_DIR_NAME}/
        cd ${OPENH264_DIR_NAME} && patch -p1 < openh264-1.0.0-android21.patch || true
    fi
    cd ${BASEDIR}
    ./openh264-build-target-archs || true
fi

if [ "$DOWNLOAD_OPUS" == "1" ]
then
    # see https://trac.pjsip.org/repos/ticket/1904
    echo "Downloading Opus ..."
    cd "${BASEDIR}"
    curl -L -# -o opus.tar.gz "$OPUS_DOWNLOAD_URL" 2>&1
    rm -rf "${OPUS_DIR_NAME}"
    export PATH="${BASEDIR}/${NDK_DIR_NAME}:$PATH"
    echo "Opus downloaded!"
    echo "Extracting Opus ..."
    tar xzf opus.tar.gz && rm -rf opus.tar.gz
    cd ${OPUS_DIR_NAME}
    mkdir jni
    cat <<EOF > jni/Application.mk
APP_ABI             := ${TARGET_ARCHS[@]}
EOF
    cat <<'EOF' > jni/Android.mk
LOCAL_PATH := $(call my-dir)/..
include $(CLEAR_VARS)
include $(LOCAL_PATH)/celt_sources.mk
include $(LOCAL_PATH)/silk_sources.mk
include $(LOCAL_PATH)/opus_sources.mk
LOCAL_MODULE        := opus
SILK_SOURCES        += $(SILK_SOURCES_FIXED)
CELT_SOURCES        += $(CELT_SOURCES_ARM)
SILK_SOURCES        += $(SILK_SOURCES_ARM)
LOCAL_SRC_FILES     := \
    $(CELT_SOURCES) $(SILK_SOURCES) $(OPUS_SOURCES) $(OPUS_SOURCES_FLOAT)
LOCAL_LDLIBS        := -lm -llog
LOCAL_C_INCLUDES    := \
    $(LOCAL_PATH)/include \
    $(LOCAL_PATH)/silk \
    $(LOCAL_PATH)/silk/fixed \
    $(LOCAL_PATH)/celt
LOCAL_CFLAGS        := -DNULL=0 -DSOCKLEN_T=socklen_t -DLOCALE_NOT_USED -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64
LOCAL_CFLAGS        += -Drestrict='' -D__EMX__ -DOPUS_BUILD -DFIXED_POINT -DUSE_ALLOCA -DHAVE_LRINT -DHAVE_LRINTF -O3 -fno-math-errno
LOCAL_CPPFLAGS      := -DBSD=1 
LOCAL_CPPFLAGS      += -ffast-math -O3 -funroll-loops
include $(BUILD_STATIC_LIBRARY)
EOF
    ndk-build
    mkdir -p $OPUS_DEV_LIB/include/opus
    mkdir -p $OPUS_DEV_LIB/lib
    cp include/* $OPUS_DEV_LIB/include/opus/
    cp -r obj/local/* $OPUS_DEV_LIB/lib/
fi

echo "The build system is ready! Execute: ./build to build PJSIP :)"
